title: Benjamin GILBERT
url: "https://bglbrt.github.io"
baseurl: ""

markdown: kramdown

sass:
    style: compressed
    sass_dir: _sass

favicon: true

nav:
  - name: "About"
    link: "/en/about"
    lang: "en"
  - name: "Research"
    link: "/en/research"
    lang: "en"
  - name: "Teaching"
    link: "/en/teaching"
    lang: "en"
  - name: "Resume"
    link: "/en/resume.pdf"
    lang: "en"
  - name: "Contact"
    link: "/en/contact"
    lang: "en"
  - name: "Ã€ propos"
    link: "/"
    lang: "fr"
  - name: "Recherche"
    link: "/fr/recherche"
    lang: "fr"
  - name: "Enseignement"
    link: "/fr/enseignement"
    lang: "fr"
  - name: "CV"
    link: "/fr/CV.pdf"
    lang: "fr"
  - name: "Contact"
    link: "/fr/contact"
    lang: "fr"